import type { MoveMapData } from "../types/move-map";
import { budgetTotals, conversationFocus, documentWatch, keyRisks, topOpenDecisions, upcomingTasks } from "../lib/selectors";
import { formatCurrencyRange, formatDate } from "../lib/formatters";
import { PageHeader } from "../components/PageHeader";
import { SectionCard } from "../components/SectionCard";
import { RouteLine } from "../components/RouteLine";
import { ConversationCard } from "../components/ConversationCard";
import { DecisionPostcard } from "../components/DecisionPostcard";
import { ConfidenceBadge } from "../components/ConfidenceBadge";
import { StatusPill } from "../components/StatusPill";
import { PrintActions } from "../components/PrintActions";

export function HomeView({ data }: { data: MoveMapData }) {
  const oneTime = budgetTotals(data.budget_items, "one_time");
  const monthly = budgetTotals(data.budget_items, "monthly");
  return <div className="view"><PageHeader eyebrow="Family move atlas" title="A calm map for the Barcelona question">See what is known, what is uncertain, and what deserves the next family conversation.</PageHeader><section className="hero-card"><div><p className="eyebrow">Move at a glance</p><h2>{data.plan.origin} → {data.plan.destination}</h2><p>{data.plan.household_summary}</p><p className="small-text">Target timing: {formatDate(data.plan.target_move_date)} · Last updated {formatDate(data.plan.last_updated)}</p></div><PrintActions data={data} /></section><RouteLine tracks={data.planning_tracks} /><section className="dashboard-grid"><SectionCard title="Readiness by track" kicker="Where the plan stands"><div className="track-list">{data.planning_tracks.map((t)=><div className="track-row" key={t.id}><div><strong>{t.title}</strong><p>{t.next_action}</p></div><ConfidenceBadge confidence={t.confidence}/><StatusPill status={t.readiness}/></div>)}</div></SectionCard><SectionCard title="Conversation focus" kicker="Read aloud together">{conversationFocus(data).map((idea)=><ConversationCard key={idea.id} idea={idea}/>)}</SectionCard><SectionCard title="Top open decisions" kicker="Decision postcards">{topOpenDecisions(data).map((d)=><DecisionPostcard key={d.id} decision={d} options={data.options}/>)}</SectionCard><SectionCard title="Budget range snapshot" kicker="Ranges, not false precision"><div className="metric-pair"><div><span>One-time move range</span><strong>{formatCurrencyRange(oneTime.low, oneTime.high, "USD")}</strong></div><div><span>Monthly range</span><strong>{formatCurrencyRange(monthly.low, monthly.high, "EUR")}</strong></div></div><p className="small-text">Placeholder ranges until source-checked research replaces them.</p></SectionCard><SectionCard title="Next practical steps" kicker="Small enough to act on"><ul className="clean-list">{upcomingTasks(data).map((t)=><li key={t.id}><strong>{t.title}</strong><span>{t.track} · {formatDate(t.due_date)}</span></li>)}</ul></SectionCard><SectionCard title="Key risks with mitigations" kicker="Uncertainty made useful"><ul className="clean-list">{keyRisks(data).map((r)=><li key={r.id}><strong>{r.title}</strong><span>{r.mitigation}</span></li>)}</ul></SectionCard><SectionCard title="Document timing watch" kicker="Paperwork without panic"><ul className="clean-list">{documentWatch(data).map((d)=><li key={d.id}><strong>{d.name}</strong><span>{d.needed_for} · due {formatDate(d.due_date)}</span></li>)}</ul></SectionCard><SectionCard title="Latest snapshot" kicker="Preserve today’s thinking"><p>{data.snapshots[0]?.title}</p><p className="small-text">{data.snapshots[0]?.notes}</p></SectionCard></section></div>;
}
